### ISSUE TITLE
The password provided does not seem to unlock the zip

### ISSUE THREAD

**Issue by weissercn** [WHUIR/MATINF#1]
Thanks for a great dataset. When filling out the forms in order to access the dataset, I received a password alongside a download link. As 7z does not exist for Mac, I tried to unzip it with osx's Archive Utility, but the password does not seem to match.

**Comment by JetRunner** [comment]
Hi @weissercn, thanks for ur interest in our work! Yes, macOS's Archive Utility cannot uncompress the file. The password is correct but you need 7zip. Here is a link you may find useful about 7zip on Mac.
https://apple.stackexchange.com/questions/307377/how-can-i-unpack-7z-files-via-macos-terminal

**Comment by weissercn** [comment]
Thank you! Installing p7zip with homebrew worked.
