### ISSUE TITLE
Where can we get a copy of ChineseEmbedding.txt?

### ISSUE THREAD

**Issue by ManWan888** [WHUIR/MATINF#4]
In vocab.py:

if name == 'main':
print('Building vocab...')
vocab = Vocab.build('./data/train.csv')
vocab.save('./data/vocab.json')

print('Building embeddings...')
embeddings = build_embeddings('./data/ChineseEmbedding.txt', vocab)

However, I do not get the ChineseEmbedding.txt in data set.

Should we get the ChineseEmbedding.txt from other location?

Thanks

**Comment by JetRunner** [comment]
Yep. You can use your own embedding or download one. 

E.g., https://ai.tencent.com/ailab/nlp/en/embedding.html

**Comment by ManWan888** [comment]
JetRunner, Thank you for your comment. Best regards,

**Comment by ManWan888** [comment]
Thank you for your comment. Best regards,
